version: '2.1'
orbs:
  nx: nrwl/nx@1.6.0
jobs:
  build:
    docker:
      - image: 'cimg/node:14.17-browsers'
    steps:
      - checkout
      - run:
          command: yarn install --frozen-lockfile
          name: Install dependencies
      - nx/set-shas
      - run:
          command: >-
            yarn nx affected --target=build --base=$NX_BASE --parallel
            --max-parallel=3
          name: Run Builds
      - run:
          command: >-
            yarn nx affected --target=test --base=$NX_BASE --parallel
            --max-parallel=2
          name: Run Unit Tests
workflows: null